# Change these first
owner: freshairradio # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Website
    url: https://freshair.radio
  - name: Members Portal
    url: https://members.freshair.radio
  - name: API
    url: https://api.freshair.radio

status-website:
  baseUrl: /status
  logoUrl: https://cdn.freshair.radio/logos/FreshairBlackLogo.png
  name: FreshAir
  introTitle: "Edinburgh's student radio"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Site
      href: https://freshair.radio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
